#!/bin/sh
# ~/.local/bin/sway-switch
sel=$(swaymsg -t get_tree | jq -r '
  .. | select(.type?=="con" or .type?=="floating_con")
  | select(.nodes==[] and .name!=null)
  | "\(.id)\t\(.app_id // .window_properties.class)  —  \(.name)"
' | fuzzel --dmenu -p "win> ")

[ -n "$sel" ] || exit
id=${sel%%$'\t'*}
swaymsg "[con_id=$id] focus"
